<?php

/**
 * BaseWordRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $object_id
 * @property Word $Word
 * 
 * @method integer      getObjectId()  Returns the current record's "object_id" value
 * @method Word         getWord()      Returns the current record's "Word" value
 * @method WordRevision setObjectId()  Sets the current record's "object_id" value
 * @method WordRevision setWord()      Sets the current record's "Word" value
 * 
 * @package    rechnik
 * @subpackage model
 * @author     borislav
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseWordRevision extends Revision
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('word_revision');
        $this->hasColumn('object_id', 'integer', 3, array(
             'type' => 'integer',
             'length' => '3',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Word', array(
             'local' => 'object_id',
             'foreign' => 'id'));
    }
}