<?php

/**
 * BaseIncorrectFormRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $object_id
 * @property IncorrectForm $IncorrectForm
 * 
 * @method integer               getObjectId()      Returns the current record's "object_id" value
 * @method IncorrectForm         getIncorrectForm() Returns the current record's "IncorrectForm" value
 * @method IncorrectFormRevision setObjectId()      Sets the current record's "object_id" value
 * @method IncorrectFormRevision setIncorrectForm() Sets the current record's "IncorrectForm" value
 * 
 * @package    rechnik
 * @subpackage model
 * @author     borislav
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseIncorrectFormRevision extends Revision
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('incorrect_form_revision');
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IncorrectForm', array(
             'local' => 'object_id',
             'foreign' => 'id'));
    }
}