<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $realname
 * @property string $email
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer            getUserId()      Returns the current record's "user_id" value
 * @method string             getRealname()    Returns the current record's "realname" value
 * @method string             getEmail()       Returns the current record's "email" value
 * @method sfGuardUser        getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method sfGuardUserProfile setUserId()      Sets the current record's "user_id" value
 * @method sfGuardUserProfile setRealname()    Sets the current record's "realname" value
 * @method sfGuardUserProfile setEmail()       Sets the current record's "email" value
 * @method sfGuardUserProfile setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    rechnik
 * @subpackage model
 * @author     borislav
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('realname', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
        $this->hasColumn('email', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}