<?php

/**
 * BaseWordType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $idi_number
 * @property string $speech_part
 * @property clob $comment
 * @property clob $rules
 * @property clob $rules_test
 * @property string $example_word
 * @property Doctrine_Collection $Words
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getIdiNumber()    Returns the current record's "idi_number" value
 * @method string              getSpeechPart()   Returns the current record's "speech_part" value
 * @method clob                getComment()      Returns the current record's "comment" value
 * @method clob                getRules()        Returns the current record's "rules" value
 * @method clob                getRulesTest()    Returns the current record's "rules_test" value
 * @method string              getExampleWord()  Returns the current record's "example_word" value
 * @method Doctrine_Collection getWords()        Returns the current record's "Words" collection
 * @method WordType            setId()           Sets the current record's "id" value
 * @method WordType            setName()         Sets the current record's "name" value
 * @method WordType            setIdiNumber()    Sets the current record's "idi_number" value
 * @method WordType            setSpeechPart()   Sets the current record's "speech_part" value
 * @method WordType            setComment()      Sets the current record's "comment" value
 * @method WordType            setRules()        Sets the current record's "rules" value
 * @method WordType            setRulesTest()    Sets the current record's "rules_test" value
 * @method WordType            setExampleWord()  Sets the current record's "example_word" value
 * @method WordType            setWords()        Sets the current record's "Words" collection
 * 
 * @package    rechnik
 * @subpackage model
 * @author     borislav
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseWordType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('word_type');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('idi_number', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('speech_part', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             ));
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('rules', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('rules_test', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('example_word', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Word as Words', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}