<?php

/**
 * BaseRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $field
 * @property clob $old_value
 * @property clob $new_value
 * @property integer $user_id
 * @property boolean $is_pattrolled
 * @property sfGuardUser $User
 * 
 * @method string      getField()         Returns the current record's "field" value
 * @method clob        getOldValue()      Returns the current record's "old_value" value
 * @method clob        getNewValue()      Returns the current record's "new_value" value
 * @method integer     getUserId()        Returns the current record's "user_id" value
 * @method boolean     getIsPattrolled()  Returns the current record's "is_pattrolled" value
 * @method sfGuardUser getUser()          Returns the current record's "User" value
 * @method Revision    setField()         Sets the current record's "field" value
 * @method Revision    setOldValue()      Sets the current record's "old_value" value
 * @method Revision    setNewValue()      Sets the current record's "new_value" value
 * @method Revision    setUserId()        Sets the current record's "user_id" value
 * @method Revision    setIsPattrolled()  Sets the current record's "is_pattrolled" value
 * @method Revision    setUser()          Sets the current record's "User" value
 * 
 * @package    rechnik
 * @subpackage model
 * @author     borislav
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BaseRevision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('revision');
        $this->hasColumn('field', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('old_value', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('new_value', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('is_pattrolled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));


        $this->index('field', array(
             'fields' => 
             array(
              0 => 'field',
             ),
             ));
        $this->index('is_pattrolled', array(
             'fields' => 
             array(
              0 => 'is_pattrolled',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}