<?php
// auto-generated by sfViewConfigHandler
// date: 2016/12/27 06:26:37
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('description', 'Речник на българския език. Включва в себе си следните речници: тълковен, правописен, синонимен, словоформен. Свободен софтуер.', false, false);
  $response->addMeta('keywords', 'български език, речник, тълковен, правописен, синонимен, словоформи', false, false);




