<?php

/**
 * WordTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rechnik
 * @subpackage model
 * @author     borislav
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class WordTranslation extends BaseWordTranslation
{

}