<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/11/26 13:22:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=chitanka_rechko',
  'username' => 'chitanka',
  'password' => 'ch1tanka',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_general_ci',
    'default_table_charset' => 'utf8',
    'use_native_enum' => true,
  ),
  'name' => 'doctrine',
)),);
